import type { CSSProperties } from "react";
import type { Theme } from "./types";

export type ThemeStyles = Record<string, string>;

const sharedExtras = {
  violet: {
    accentGlow: "from-indigo-500/20",
    aspectActive: "bg-indigo-500/15 border border-indigo-500/30 text-indigo-200 font-bold",
    aspectInactive: "bg-white/5 border border-white/10 text-white",
    aspectActiveBadge: "bg-indigo-500 text-white",
    aspectInactiveBadge: "bg-white/10 text-slate-400",
    retryButton: "bg-white/5 hover:bg-white/10 text-slate-300 border-white/15",
    footer: "border-white/10 text-slate-500 bg-transparent",
  },
  dark: {
    accentGlow: "from-indigo-500/15",
    aspectActive: "bg-indigo-950/40 border border-indigo-500/30 text-indigo-200 font-bold",
    aspectInactive: "bg-slate-950/40 border border-slate-800/80 text-slate-200",
    aspectActiveBadge: "bg-indigo-600 text-white",
    aspectInactiveBadge: "bg-slate-900 text-slate-500",
    retryButton: "bg-slate-950/40 hover:bg-slate-950/60 text-slate-300 border-slate-800",
    footer: "border-slate-800 text-slate-500 bg-transparent",
  },
  light: {
    accentGlow: "from-indigo-500/10",
    aspectActive: "bg-indigo-50 border-indigo-200 text-indigo-800 font-bold",
    aspectInactive: "bg-slate-50 border border-slate-200 text-slate-800",
    aspectActiveBadge: "bg-indigo-600 text-white",
    aspectInactiveBadge: "bg-slate-200 text-slate-500",
    retryButton: "bg-slate-100 hover:bg-slate-200 text-slate-700 border-slate-200",
    footer: "border-slate-200 text-slate-500 bg-white/50",
  },
};

export const THEME_STYLES: Record<Theme, ThemeStyles> = {
  violet: {
    rootBg: "bg-[#0f172a] text-slate-100",
    rootBgStyle: "",
    headerBg: "bg-white/5 border-white/10 backdrop-blur-md",
    headerTitle: "text-white",
    headerSubtitle: "text-slate-400",
    sessionText: "text-slate-400",
    sessionTopic: "text-indigo-300",
    divider: "bg-white/10",
    banner: "bg-white/5 border border-white/10 backdrop-blur-xl",
    bannerTitle: "text-white",
    bannerDesc: "text-slate-300",
    bannerStep: "bg-white/5 border border-white/5 text-slate-300",
    filterConsole: "bg-white/5 border border-white/10 backdrop-blur-md",
    input: "bg-white/5 border-white/10 text-white placeholder:text-slate-500 focus:bg-[#1e293b] focus:border-indigo-500",
    filterCount: "bg-white/5 border-white/5 text-slate-400 border-white/10",
    themePillLabel: "text-slate-400",
    pillActive: "bg-indigo-500 border-indigo-400 text-white shadow-md shadow-indigo-500/20",
    pillInactive: "bg-white/5 border-white/10 text-slate-300 hover:bg-white/10 hover:border-white/20",
    card: "bg-white/5 border border-white/10 hover:bg-white/10 hover:border-white/20 text-slate-100",
    cardTag: "bg-indigo-500/20 text-indigo-300",
    cardFormat: "border border-white/10 bg-white/5 text-slate-400",
    cardTitle: "text-white group-hover:text-indigo-300",
    cardSub: "text-slate-500",
    cardDivider: "border-white/10",
    cardLabel: "text-slate-400",
    cardBulletText: "text-slate-300",
    cardFooter: "border-white/5 text-indigo-400 group-hover:text-indigo-300",
    workflowCard: "bg-white/10 backdrop-blur-2xl border border-white/20 text-slate-100",
    workflowHeading: "text-white",
    workflowSubtitle: "text-slate-400",
    aspectLabel: "text-indigo-300",
    aspectItem: "bg-white/5 border border-white/10 text-white",
    aspectNum: "bg-white/10 text-indigo-300",
    aspectCheckedItem: "bg-indigo-500/15 border border-indigo-500/30 text-indigo-200 font-bold",
    aspectCheckedNum: "bg-indigo-500 text-white",
    aspectUncheckedNum: "bg-white/10 text-slate-400",
    aspectCheckedText: "line-through opacity-60 text-slate-400",
    timerLabel: "text-[#94a3b8]",
    timerSub: "text-slate-400",
    circularTrack: "stroke-white/5",
    circularIndicator: "stroke-amber-400",
    clockIcon: "text-amber-400",
    clockTime: "text-white",
    clockLabel: "text-slate-400",
    cancelButton: "bg-white/5 hover:bg-white/10 text-slate-300 border-white/15",
    tipsFooter: "text-slate-500 border-t border-white/5",
    bufferLabel: "text-indigo-400",
    bufferHeading: "text-white",
    bufferDesc: "text-slate-400",
    bufferCircle: "bg-indigo-500 border-indigo-400 text-white shadow-indigo-500/25",
    bufferFooter: "text-slate-500",
    recordCol: "bg-red-500/5",
    recordLabel: "text-slate-400",
    recordTrackerLabel: "text-indigo-300",
    recordAspectCount: "text-amber-300",
    recordTimerContainer: "bg-white/5 border border-white/20",
    recordTimerLabel: "text-slate-400",
    recordTimerValue: "text-white",
    recordCancelBtn: "bg-white/5 hover:bg-white/10 text-slate-300 border border-white/10",
    recordTipsBox: "bg-white/5 border border-white/5 text-slate-400",
    recordTipsHeader: "text-indigo-300",
    recordTipsItalic: "text-slate-400",
    recordStorageFoot: "text-slate-500",
    resultBanner: "bg-white/5 border border-white/10 backdrop-blur-md",
    resultBadge: "bg-emerald-500/10 text-emerald-300 border-emerald-500/20",
    resultHeading: "text-white",
    resultDesc: "text-slate-300",
    resultAccentWord: "text-indigo-300",
    resultFileCard: "bg-white/5 border border-white/10 text-white",
    resultFileLabel: "text-[9px] text-slate-400",
    resultDivider: "border-white/15",
    resultSectionTitle: "text-white",
    resultPanel: "bg-white/5 border border-white/10 backdrop-blur-md",
    resultInnerLabel: "text-slate-300",
    resultPlayerContainer: "bg-white/5 border border-white/10",
    resultPlayerFoot: "text-slate-500",
    scoreSectionLabel: "text-indigo-300",
    scoreBullet: "text-emerald-400",
    checkedBonusCard: "bg-indigo-500/10 border-indigo-500/20",
    uncheckedBonusCard: "bg-white/5 border-white/10 opacity-70",
    bonusCardTitle: "text-white",
    bonusCardDesc: "text-slate-400",
    rubricCard: "bg-white/5 border border-white/10 backdrop-blur-md",
    rubricTitle: "text-white",
    rubricDesc: "text-slate-400",
    rubricItem: "hover:bg-white/5 border-white/5",
    rubricItemChecked: "bg-emerald-500/10 text-emerald-200 border-emerald-500/20",
    rubricItemUnchecked: "bg-white/5 border-white/10 text-slate-300",
    rubricCheckText: "text-slate-300 font-medium",
    rubricButtonOk: "bg-indigo-500 hover:bg-indigo-600 text-white",
    rubricButtonCancel: "bg-white/5 hover:bg-white/10 text-slate-300 border border-white/15",
    emptyBanner: "bg-white/5 border border-dashed border-white/10",
    emptyTitle: "text-white",
    emptyDesc: "text-slate-400",
    ...sharedExtras.violet,
  },
  dark: {
    rootBg: "bg-[#090d16] text-slate-200",
    rootBgStyle: "",
    headerBg: "bg-slate-950/50 border-slate-800 backdrop-blur-md",
    headerTitle: "text-slate-100",
    headerSubtitle: "text-slate-500",
    sessionText: "text-slate-500",
    sessionTopic: "text-indigo-400",
    divider: "bg-slate-800",
    banner: "bg-slate-900/40 border border-slate-800/80 backdrop-blur-xl",
    bannerTitle: "text-slate-100",
    bannerDesc: "text-slate-400",
    bannerStep: "bg-slate-950/40 border border-slate-900 text-slate-400",
    filterConsole: "bg-slate-900/40 border border-slate-800 backdrop-blur-md",
    input: "bg-slate-950/40 border-slate-800 text-slate-100 placeholder:text-slate-600 focus:bg-[#111827] focus:border-indigo-500",
    filterCount: "bg-slate-950/40 border-slate-900 text-slate-400 border border-slate-800",
    themePillLabel: "text-slate-500",
    pillActive: "bg-indigo-600 border-indigo-500 text-white shadow-md shadow-indigo-600/20",
    pillInactive: "bg-slate-950/40 border-slate-800 text-slate-400 hover:bg-slate-950/60 hover:border-slate-700",
    card: "bg-slate-900/60 border border-slate-800/80 hover:bg-slate-900 hover:border-slate-700 text-slate-200",
    cardTag: "bg-indigo-500/10 text-indigo-400",
    cardFormat: "border border-slate-800/50 bg-slate-950/30 text-slate-400",
    cardTitle: "text-slate-100 group-hover:text-indigo-300",
    cardSub: "text-slate-600",
    cardDivider: "border-slate-800/60",
    cardLabel: "text-slate-500",
    cardBulletText: "text-slate-400",
    cardFooter: "border-slate-800 text-indigo-400 group-hover:text-indigo-300",
    workflowCard: "bg-slate-900/80 backdrop-blur-2xl border border-slate-800 text-slate-200",
    workflowHeading: "text-slate-100",
    workflowSubtitle: "text-slate-500",
    aspectLabel: "text-indigo-400",
    aspectItem: "bg-slate-950/40 border border-slate-800/80 text-slate-200",
    aspectNum: "bg-slate-900 text-indigo-400",
    aspectCheckedItem: "bg-indigo-950/40 border border-indigo-500/30 text-indigo-200 font-bold",
    aspectCheckedNum: "bg-indigo-600 text-white",
    aspectUncheckedNum: "bg-slate-900 text-slate-500",
    aspectCheckedText: "line-through opacity-50 text-slate-500",
    timerLabel: "text-slate-500",
    timerSub: "text-slate-600",
    circularTrack: "stroke-slate-900/50",
    circularIndicator: "stroke-amber-500",
    clockIcon: "text-amber-500",
    clockTime: "text-slate-100",
    clockLabel: "text-slate-500",
    cancelButton: "bg-slate-950/40 hover:bg-slate-950/60 text-slate-300 border-slate-800",
    tipsFooter: "text-slate-600 border-t border-slate-800/60",
    bufferLabel: "text-indigo-400",
    bufferHeading: "text-slate-100",
    bufferDesc: "text-slate-500",
    bufferCircle: "bg-indigo-600 border-indigo-500 text-white shadow-indigo-600/25",
    bufferFooter: "text-slate-600",
    recordCol: "bg-red-500/5",
    recordLabel: "text-slate-500",
    recordTrackerLabel: "text-indigo-400",
    recordAspectCount: "text-amber-400",
    recordTimerContainer: "bg-slate-950/40 border border-slate-800",
    recordTimerLabel: "text-slate-500",
    recordTimerValue: "text-slate-100",
    recordCancelBtn: "bg-slate-950/40 hover:bg-slate-950/60 text-slate-300 border border-slate-800",
    recordTipsBox: "bg-slate-950/40 border border-slate-800 text-slate-400",
    recordTipsHeader: "text-indigo-400",
    recordTipsItalic: "text-slate-500",
    recordStorageFoot: "text-slate-600",
    resultBanner: "bg-slate-900/40 border border-slate-800 backdrop-blur-md",
    resultBadge: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
    resultHeading: "text-slate-100",
    resultDesc: "text-slate-400",
    resultAccentWord: "text-indigo-400",
    resultFileCard: "bg-slate-950/40 border-slate-800 text-slate-200",
    resultFileLabel: "text-[9px] text-slate-500",
    resultDivider: "border-slate-800",
    resultSectionTitle: "text-slate-100",
    resultPanel: "bg-slate-900/40 border border-slate-800 backdrop-blur-md",
    resultInnerLabel: "text-slate-400",
    resultPlayerContainer: "bg-slate-950/40 border border-slate-800",
    resultPlayerFoot: "text-slate-600",
    scoreSectionLabel: "text-indigo-400",
    scoreBullet: "text-emerald-500",
    checkedBonusCard: "bg-indigo-950/20 border-indigo-500/20",
    uncheckedBonusCard: "bg-slate-950/40 border border-slate-800 opacity-60",
    bonusCardTitle: "text-slate-100",
    bonusCardDesc: "text-slate-500",
    rubricCard: "bg-slate-900/40 border border-slate-800 backdrop-blur-md",
    rubricTitle: "text-slate-100",
    rubricDesc: "text-slate-500",
    rubricItem: "hover:bg-slate-950/30 border-slate-900",
    rubricItemChecked: "bg-emerald-500/10 text-emerald-300 border-emerald-500/20",
    rubricItemUnchecked: "bg-slate-950/40 border border-slate-800 text-slate-400",
    rubricCheckText: "text-slate-300 font-medium",
    rubricButtonOk: "bg-indigo-600 hover:bg-indigo-500 text-white",
    rubricButtonCancel: "bg-slate-950/40 hover:bg-slate-950/60 text-slate-400 border border-slate-800",
    emptyBanner: "bg-slate-900/40 border border-dashed border-slate-800",
    emptyTitle: "text-slate-100",
    emptyDesc: "text-slate-500",
    ...sharedExtras.dark,
  },
  light: {
    rootBg: "bg-[#f8fafc] text-slate-800",
    rootBgStyle: "",
    headerBg: "bg-white/70 border-slate-200/80 backdrop-blur-md shadow-xs",
    headerTitle: "text-slate-900",
    headerSubtitle: "text-slate-500",
    sessionText: "text-slate-500",
    sessionTopic: "text-indigo-600 font-semibold",
    divider: "bg-slate-200",
    banner: "bg-white border border-slate-200 shadow-xs",
    bannerTitle: "text-slate-900",
    bannerDesc: "text-slate-600",
    bannerStep: "bg-slate-50 border border-slate-100 text-slate-600",
    filterConsole: "bg-white border border-slate-200 shadow-xs",
    input: "bg-slate-50 border-slate-200/80 text-slate-900 placeholder:text-slate-400 focus:bg-white focus:border-indigo-600",
    filterCount: "bg-slate-100 border border-slate-200 text-slate-600",
    themePillLabel: "text-slate-500",
    pillActive: "bg-indigo-600 border-indigo-500 text-white shadow-xs",
    pillInactive: "bg-slate-100 border-slate-200 text-slate-600 hover:bg-slate-200 hover:border-slate-300",
    card: "bg-white border border-slate-200 shadow-xs hover:bg-slate-50/70 hover:border-slate-300 hover:shadow-xs text-slate-800",
    cardTag: "bg-indigo-50 text-indigo-700 font-bold",
    cardFormat: "border border-slate-200 bg-slate-100 text-slate-600",
    cardTitle: "text-slate-900 group-hover:text-indigo-600",
    cardSub: "text-slate-500",
    cardDivider: "border-slate-200",
    cardLabel: "text-slate-500",
    cardBulletText: "text-slate-600",
    cardFooter: "border-slate-100 text-indigo-600 group-hover:text-indigo-700",
    workflowCard: "bg-white border border-slate-200 shadow-md text-slate-800",
    workflowHeading: "text-slate-900",
    workflowSubtitle: "text-slate-500",
    aspectLabel: "text-indigo-600",
    aspectItem: "bg-slate-50 border border-slate-200 text-slate-800",
    aspectNum: "bg-slate-200 text-slate-600",
    aspectCheckedItem: "bg-indigo-50 border-indigo-200 text-indigo-800 font-bold",
    aspectCheckedNum: "bg-indigo-600 text-white",
    aspectUncheckedNum: "bg-slate-200 text-slate-500",
    aspectCheckedText: "line-through opacity-40 text-slate-400",
    timerLabel: "text-slate-500",
    timerSub: "text-slate-500",
    circularTrack: "stroke-slate-100",
    circularIndicator: "stroke-indigo-600",
    clockIcon: "text-indigo-600",
    clockTime: "text-slate-900",
    clockLabel: "text-slate-500",
    cancelButton: "bg-slate-100 hover:bg-slate-200 text-slate-700 border border-slate-200",
    tipsFooter: "text-slate-500 border-t border-slate-200",
    bufferLabel: "text-indigo-600",
    bufferHeading: "text-slate-900",
    bufferDesc: "text-slate-500",
    bufferCircle: "bg-indigo-600 border-indigo-500 text-white shadow-sm",
    bufferFooter: "text-slate-500",
    recordCol: "bg-slate-50/50",
    recordLabel: "text-slate-500",
    recordTrackerLabel: "text-indigo-600",
    recordAspectCount: "text-amber-700",
    recordTimerContainer: "bg-slate-50 border border-slate-200",
    recordTimerLabel: "text-slate-500",
    recordTimerValue: "text-slate-900",
    recordCancelBtn: "bg-slate-100 hover:bg-slate-200 text-slate-700 border-slate-200",
    recordTipsBox: "bg-slate-50 border border-slate-200 text-slate-600",
    recordTipsHeader: "text-indigo-600",
    recordTipsItalic: "text-slate-500",
    recordStorageFoot: "text-slate-500",
    resultBanner: "bg-white border border-slate-200 shadow-xs",
    resultBadge: "bg-emerald-50 text-emerald-800 border border-emerald-200",
    resultHeading: "text-slate-900",
    resultDesc: "text-slate-600",
    resultAccentWord: "text-indigo-600",
    resultFileCard: "bg-slate-50 border border-slate-200 text-slate-800",
    resultFileLabel: "text-[9px] text-slate-500",
    resultDivider: "border-slate-200",
    resultSectionTitle: "text-slate-900",
    resultPanel: "bg-white border border-slate-200 shadow-xs",
    resultInnerLabel: "text-slate-600",
    resultPlayerContainer: "bg-slate-50 border border-slate-200",
    resultPlayerFoot: "text-slate-500",
    scoreSectionLabel: "text-indigo-600",
    scoreBullet: "text-emerald-600",
    checkedBonusCard: "bg-indigo-50 border-indigo-200 text-indigo-900",
    uncheckedBonusCard: "bg-slate-50 border border-slate-200 opacity-60",
    bonusCardTitle: "text-slate-800",
    bonusCardDesc: "text-slate-500",
    rubricCard: "bg-white border border-slate-200 shadow-xs",
    rubricTitle: "text-slate-950",
    rubricDesc: "text-slate-500",
    rubricItem: "hover:bg-slate-50 border-slate-100",
    rubricItemChecked: "bg-emerald-50 text-emerald-800 border-emerald-200",
    rubricItemUnchecked: "bg-slate-50 border border-slate-200 text-slate-700",
    rubricCheckText: "text-slate-800 font-medium",
    rubricButtonOk: "bg-indigo-600 hover:bg-indigo-500 text-white",
    rubricButtonCancel: "bg-slate-100 hover:bg-slate-200 text-slate-700 border-slate-200",
    emptyBanner: "bg-white border border-dashed border-slate-300",
    emptyTitle: "text-slate-900",
    emptyDesc: "text-slate-500",
    ...sharedExtras.light,
  },
};

export const ROOT_BG_STYLES: Record<Theme, CSSProperties> = {
  violet: {
    backgroundImage:
      "radial-gradient(at 0% 0%, rgba(79, 70, 229, 0.4) 0px, transparent 50%), radial-gradient(at 100% 100%, rgba(192, 38, 211, 0.4) 0px, transparent 50%)",
  },
  dark: {
    backgroundImage:
      "radial-gradient(at 0% 0%, rgba(30, 41, 59, 0.3) 0px, transparent 50%), radial-gradient(at 100% 100%, rgba(15, 23, 42, 0.3) 0px, transparent 50%)",
  },
  light: {
    backgroundImage:
      "radial-gradient(at 0% 0%, rgba(203, 213, 225, 0.3) 0px, transparent 50%), radial-gradient(at 100% 100%, rgba(241, 245, 249, 0.4) 0px, transparent 50%)",
  },
};
